export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  BUSINESS_OWNER: 'BUSINESS_OWNER',
  ADMIN: 'ADMIN'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION'
};

export const ADDRESS_TYPES = {
  HOME: 'HOME',
  OFFICE: 'OFFICE',
  OTHER: 'OTHER'
};

export const OTP_TYPES = {
  LOGIN: 'LOGIN',
  REGISTRATION: 'REGISTRATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION'
};

export const DEVICE_TYPES = {
  WEB: 'WEB',
  ANDROID: 'ANDROID',
  IOS: 'IOS'
};