spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/waterwala_users
    username: root
    password: Raju21@Axe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

# Session management configuration
session:
  redis:
    enabled: true
    default-timeout-days: 30
  cleanup:
    enabled: true
    interval: "0 0 2 * * ?" # Daily at 2 AM