package productservice.model;

public enum ProductCategory {
    WATER_CANS, WATER_CONTAINERS, BULK_WATER, WATER_TANKS,
    INSTALLATION_SERVICES, MAINTENANCE_SERVICES, EQUIPMENT_RENTAL,
    WATER_TESTING, PURIFIERS, ACCESSORIES
}
